Feat/recv2- Recording functionality
NeuroML/pyNeuroML pull request #342
Opened 2024-04-18 19:52 UTC by AdityaBITMESRA

Updated the create_new_vispy_canvas code to add video recording functionality

2024-04-19 14:42 UTC, AdityaBITMESRA commented
Hi sir @sanjayankur31. Can you take a look at this?

2024-04-23 15:51 UTC, sanjayankur31 requested changes
It doesn't currently work for me. Please see the comments (and test it out yourself to make sure it works)

2024-04-23 15:51 UTC, sanjayankur31 commented on pyneuroml/plot/PlotMorphologyVispy.py
> +import imageio
we need to add this to the `setup.cfg` too, under the `vispy-common` extra

2024-04-23 15:51 UTC, sanjayankur31 commented on pyneuroml/plot/PlotMorphologyVispy.py
> +        output_file = f"output-{len(glob.glob('output-*.mp4'))}.mp4"
we generated the name of the output file above already---can we not re-use that here also?

2024-09-07 16:16 UTC, closed without merging