Feat/swc loaderfile  Adding SWC loader to load SWC file
NeuroML/pyNeuroML pull request #384
Opened 2024-06-05 07:38 UTC by AdityaBITMESRA

This pull request adds a new module for loading and parsing SWC files

2024-06-05 10:32 UTC, sanjayankur31 commented
Converted to a draft @AdityaBITMESRA. We'll mark it as "ready for review" once the various bits have come in.

2024-06-06 09:51 UTC, sanjayankur31 commented
- add docstrings
- docstrings should contain references to information on SWC standard and so on
- later: consider using something like networkx so that we take advantage of efficient under the hood representations: https://networkx.org/documentation/stable/#

2024-06-06 09:55 UTC, sanjayankur31 commented
- add unit tests cases for each method

2024-06-11 10:45 UTC, sanjayankur31 commented on pyneuroml/swc/LoadSWC.py
> +                    print(f"Warning: Skipping invalid line: {line}")
I'd make this a logger.error or logger.warning perhaps, and we need to decide if this should stop the parsing of the file.

2024-06-13 10:31 UTC, sanjayankur31 commented
Looking good! Notes from the meeting:

- let's leave the optimisation (networkx etc. bits) for the moment
- rather, let's focus on implementing the functions we'll need so that we have a "public API": `get_parent`, `get_children`, `get_branch_points`, and so on---a bunch of "getters"
- lets test these out and confirm that they work correctly
- later, we can optimise these under the hood

2024-06-13 10:55 UTC, AdityaBITMESRA commented
Thankyou for the instructions

2024-06-19 09:26 UTC, AdityaBITMESRA commented
Hi @sanjayankur31 , can you have a look to see if I am going correctly?

2024-06-19 09:54 UTC, sanjayankur31 commented
Sure, will try to do it today, otherwise it may have to wait for Friday---we have a full day conf/symposium tomorrow so wont' be able to get a lot of time at my desk

2024-06-25 11:03 UTC, sanjayankur31 requested changes
Looking very good @AdityaBITMESRA. It's almost there. I've left a few comments. 

In general, please do remember to use type hints and add docstrings everywhere---they're very very important and we consider them compulsory in our code.

2024-06-25 11:03 UTC, sanjayankur31 commented on pyneuroml/swc/LoadSWC.py
> +        return nodes
we probably want to return a dict with the key being the type and the value being the list of nodes of that type? 

The use case here is "give me branch points in axons and dendrites" and we'll probably want to treat them differently. If not, the user can always iterate over all the values.

2024-06-25 11:03 UTC, sanjayankur31 commented on pyneuroml/swc/LoadSWC.py
> +def parse_header(line):
don't forget the type hints and doc string :)

2024-06-25 11:03 UTC, sanjayankur31 commented on pyneuroml/swc/LoadSWC.py
> +                    print(f"Warning: Skipping invalid line: {line}")
this still needs to be updated @AdityaBITMESRA

2024-06-26 09:18 UTC, AdityaBITMESRA commented
Hi @sanjayankur31. I have addressed all the comments. Please take a look when time permits

2024-06-26 10:16 UTC, sanjayankur31 commented
Cool, I'll try to do that today. Could you check and fix the issue ruff is pointing out? (If you set up pre-commit, ruff should run on your system and fix things each time you commit---see the contributing.md file)

2024-06-26 10:33 UTC, AdityaBITMESRA commented
I have already setup pre-commit hooks but I think the ruff is pointing out to an error in PlotMorphologyVispy.py file(unused imports) which is not the file I  was working on. So what should I do?

2024-06-26 11:13 UTC, sanjayankur31 commented
Hrm, that must've been fixed in develop. Let me update your branch here on GitHub and that should fix it.

2024-06-26 11:20 UTC, sanjayankur31 commented
OK, that fixes it. Do remember to pull on your local machine so you get the updates to your branch too.

2024-06-26 11:20 UTC, AdityaBITMESRA commented
sure...thankyou

2024-07-03 15:37 UTC, sanjayankur31 commented
Looks good. I've made some tweaks in #400. Will merge that once the tests pass, and that should merge this one too.

2024-07-03 15:52 UTC, merged