Feat/export swc-Adds function to export SWC graph to a new SWC file
NeuroML/pyNeuroML pull request #404
Opened 2024-07-10 07:26 UTC by AdityaBITMESRA

1. Adds function to export SWC graph to a new SWC file
2.Adds tests to verify if generated file and input file are similar

2024-07-11 10:35 UTC, sanjayankur31 requested changes
Looks good, a few cosmetic tweaks to complete it.

2024-07-11 10:35 UTC, sanjayankur31 commented on pyneuroml/swc/LoadSWC.py
> +def export_swc(graph: SWCGraph, filename: str) -> None:
I'd add this to the `SWCGraph` class as `export_to_swc_file`. It's still SWC graph related functionality.

2024-07-11 10:35 UTC, sanjayankur31 commented on tests/swc/.coverage
Remove this file---it shouldn't be checked in. We should add `.coverage` to `.gitignore` I guess

2024-07-11 10:35 UTC, sanjayankur31 commented on tests/swc/test_LoadSWC.py
> +        # Load the original file
add a one line docstring :)

2024-07-12 13:25 UTC, AdityaBITMESRA commented
I have worked on the comments, please have a look if time permits.

2024-07-12 13:49 UTC, sanjayankur31 commented
Sounds good. Ill take a look on Monday.
-- 
Thanks,

Ankur

(Sent from mobile device)

On Fri, 12 Jul 2024, 14:26 Aditya Pandey, ***@***.***> wrote:

> I have worked on the comments, please have a look if time permits.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NeuroML/pyNeuroML/pull/404#issuecomment-2225588644>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAZBL5TA3C4AH2V33KZA4TZL7KPNAVCNFSM6AAAAABKUJJGYGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMRVGU4DQNRUGQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-07-12 14:07 UTC, merged

2024-07-12 14:07 UTC, sanjayankur31 commented
Looks good. merging this in now. Do remember to pull to update your development and other branches.